package com.example.bucket.controller;

import com.example.bucket.model.Category;
import com.example.bucket.service.CategoryService;
import com.google.gson.JsonObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class CategoriaController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    @Autowired
    private CategoryService service;

    @PostMapping(path= {"/category", "/category/"})
    public @ResponseBody JsonObject registerCategory (@RequestBody Category request) {
        return service.registerCategory(request);
    }

    @GetMapping(path={"/category", "/category/"})
    public @ResponseBody JsonObject getCategories() {
        return service.getCategories();
    }

    @GetMapping(path={"/category/{id_categoria}", "/category/{id_categoria}/"})
    public @ResponseBody JsonObject getCategoriaById(@PathVariable(value="id_categoria")int id_categoria){
        return service.getCategoryById(id_categoria);
    }
}